spring:
  application:
    name: msa-auth-api
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    oeg.hibernate.type: trace
server:
  port: 8095

security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
    resource:
      jwt:
        key-value: jwt_secret_key

jasypt:
  encryptor:
    bean: jasyptStringEncrptor
