apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-svc-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-svc-discovery
  template:
    metadata:
      labels:
        app: api-svc-discovery
    spec:
      containers:
      - image: kijaha/api-svc-discovery:1.0
        imagePullPolicy: Always
        name: api-svc-discovery
        ports:
        - containerPort: 8761