apiVersion: v1
kind: Service
metadata:
  name: api-svc-discovery
spec:
  ports:
    - port: 443
      targetPort: 8761
      protocol: TCP
  type: NodePort
  selector:
    app: api-svc-discovery