spring:
  application:
    name: msa-eureka-server
  profiles:
    active: local
server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
---
spring:  profiles: local
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
---
spring:  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka.vasd.shop/eureka/
    register-with-eureka: false
    fetch-registry: false