spring:
  application:
    name: msa-api-gateway
header:
  access-key: dml2YWtqaDI=
eureka:
  instance:
    instance-id: zuul-inst001
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8090
zuul:
  routes:
    msa-member-api:
      path: /api/member/**
      url: http://localhost:8100
      stripPrefix: false
    msa-system-api:
      path: /api/system/**
      url: http://localhost:8900
      stripPrefix: false