spring:
  application:
    name: msa-api-gateway
header:
  access-key: dml2YWtqaDI=
eureka:
  instance:
    instance-id: zuul-inst001
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8090

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    msa-member-api:
      path: /api/member/**
      url: http://localhost:8100
      stripPrefix: false
    msa-system-api:
      path: /api/system/**
      url: http://localhost:8900
      stripPrefix: false

security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
    resource:
      jwt:
        key-value: jwt_secret_key