spring:
  application:
    name: msa-member-api
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: ENC(6cKij6/UvkTIIwti6lMG3EEExhteUN35ZWWafn+PnV/TQqF+aI/1RBMMSd7s6mfFVcbmTB9TPSL3SOVhHrP4oiFyaDVliLTHoHXb8N4+Pq8=)
    username: ENC(6kasPgVaLWeVkhd4ldEtaIAwJFiMvIV9)
    password: ENC(eiZ5vp3vIT7JzViJOT8XYZRLdQ+JyXg7)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    oeg.hibernate.type: trace
server:
  port: 8100

jasypt:
  encryptor:
    bean: jasyptStringEncrptor